name: Build

on:
  workflow_dispatch:
    inputs:
      repo_github:
        description: "Repository github: example: user/repository"
        default: "vkhiep/TrollStore"
        required: true
        type: string
      ref_github:
        description: "Ref repository github: example: main, master, v.v"
        default: "main"
        required: true
        type: string
      deb_name:
        description: "Modify the name of the app on the Home Screen."
        default: "TrollStore"
        required: true
        type: string
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: ${{ inputs.repo_github }}
          ref: ${{ inputs.ref_github }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make libarchive

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 
        
      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos
      
      - name: Download iOS 16.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git && cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Build Package 
        run: |
          cd ${{ github.workspace }}
          export THEOS=${{ github.workspace }}/theos
          export THEOS=${{ github.workspace }}/theos >> ~/.profile
          make

      - name: Upload a Build Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ inputs.deb_name }}
          path: packages/*.*